DROP DATABASE IF EXISTS IMDB;
CREATE DATABASE IMDB;

\c IMDB


CREATE TABLE genre (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR NOT NULL
);

CREATE TABLE rating (
  id SERIAL PRIMARY KEY NOT NULL,
  stars INT
);

CREATE TABLE movies
(
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR NOT NULL,
  genre_id INT REFERENCES genre(id),
  img_url VARCHAR NOT NULL,
  text VARCHAR,

);

CREATE TABLE comments(
  id SERIAL PRIMARY KEY NOT NULL,
  comments VARCHAR NOT NULL,
  movies_id INT REFERENCES movies(id)
);


